{% set name = "django-upgrade" %}
{% set version = "1.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5705f7e247068f82a34b82fb74890f256e4d1ed676c539707b731471d2bb11ac

build:
  number: 0
  noarch: python
  entry_points:
    - django-upgrade = django_upgrade.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - tokenize-rt >=4.1

test:
  imports:
    - django_upgrade
  commands:
    - pip check
    - django-upgrade --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/django-upgrade
  summary: Automatically upgrade your Django projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
