schema_version: 1

context:
  name: django-upgrade
  version: "1.26.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 49c354274c8d16dc974b7791a00d6f3e1187f02ac7180e65785c17bdcfe8d0f6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - django-upgrade = django_upgrade.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - tokenize-rt >=4.1

tests:
  - python:
      imports:
        - django_upgrade
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - django-upgrade --help

about:
  summary: Automatically upgrade your Django projects.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/adamchainz/django-upgrade

extra:
  recipe-maintainers:
    - thewchan
